spring.application.name=StockTracker

finnhub.api.key=${FINNHUB_API_KEY}

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432
spring.datasource.username = 0
spring.datasource.password = 0
spring.jpa.database = POSTGRESQL
spring.jpa.show=true
spring.jpa.hibernate.dll-auto=create-drop
spring.jpa.database-plataform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

